### ISSUE TITLE
bug in CTP/simulation/src/Digitizer.cxx

### ISSUE THREAD

**Issue by mbombara** [lietava/AliceO2#5]
in AliceO2/Detectors/CTP/simulation/src/Digitizer.cxx. 
lines 47-51:
```
case o2::detectors::DetID::FV0: {
          std::bitset<CTP_NINPUTS> inpmask = std::bitset<CTP_NINPUTS>(
            (inp->mInputsMask & CTP_INPUTMASK_FT0.second).to_ullong());
          inpmaskcoll |= inpmask << CTP_INPUTMASK_FT0.first;
          break;
```
change FT0 to FV0 in FT0.second and in FT0.first

**Comment by lietava** [comment]
I fixed and asked to merge in https://github.com/AliceO2Group/AliceO2/pull/5758

**Comment by lietava** [comment]
fixed, please, test. R.

**Comment by mbombara** [comment]
> fixed, please, test. R.

I pulled, rebuild and tested - the ctpdigits.root is now empty. It has structures: bc, orbit, InputMask and ClassMask, but all of them are empty. The trigger info in ft0digits.root and fv0digits.root: bc, orbit and inputs is also empty. I run with standard:
```
o2-sim -n 10
o2-sim-digitizer-workflow -b
```
Maybe I have missed something? I pulled from lietava/AliceO2, not from official repo.

**Comment by lietava** [comment]
Hmm, do you see T0input and V0input digits created i? R.

**Comment by mbombara** [comment]
Just names in the tree structure. But if I click on leaf it is empty. Attaching screenshots for TO and V0..

<img width="1680" alt="Screenshot 2021-05-20 at 14 31 46" src="https://user-images.githubusercontent.com/30320807/118979597-e7235a80-b978-11eb-8f41-75a642669232.png">
<img width="1680" alt="Screenshot 2021-05-20 at 14 35 32" src="https://user-images.githubusercontent.com/30320807/118979626-ef7b9580-b978-11eb-8611-63a99a64e57a.png">

**Comment by lietava** [comment]
Do you use:
o2-sim -n 10 -m FT0 FV0 ITS CTP -g pythia8 -j10
o2-sim-digitizer-workflow -b
?R

**Comment by mbombara** [comment]
No, I don't and that is the problem, indeed! Thank you! When I have tried the commands:
```
o2-sim -n 10 -m FT0 FV0 ITS CTP -g pythia8 -j10
o2-sim-digitizer-workflow -b
```
The leafs are not empty now. Everything works!
BC and Orbit distro is the same in CTP (ctpdigits.root) and in T0 (ft0digits.root). There is less entries in V0 (fv0digits.root) though (8 entries in V0 and 11 in T0 and CTP).
In CTP file there is in addition CTPInputMask and CTPClassMask distros. For T0 and V0 there are mInputs (presumably active inputs from that particular detectors). I do not know if these distros are correct, for that I would need CTP configuration, I presume. 
But w.r.t to the open issue, I think it is solved and can be closed.

**Comment by lietava** [comment]
Thanks. Yes, ctp configuration is there, but database to be used. Let you now when ready. Thanks. R.
